service: spotify-liked-song-trimmer

frameworkVersion: '>=1.52.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1

plugins:
  - serverless-go-plugin
  - serverless-offline

functions:
  main:
    handler: ./functions/main/main.go
    events:
      - schedule:
          rate: rate(1 day)
          enabled: false
  test:
    handler: ./functions/test/main.go
    events:
      - http:
          path: test
          method: get
